apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: gamehouse
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp3
        resources:
          requests:
            storage: 5Gi
